### ISSUE TITLE
Define CSV to demonstrate SCD2 (address, email, ...)

### ISSUE THREAD

**Issue by de-code** [elifesciences/data-pipeline-sql-prototype#13]
Propose CSV for person data to demonstrate SCD2.

Proposal so far:

<created_date>_persons.csv

- create_date
- zip_name
- xml_file_name
- person_id
- status
- name fields: title, first_name, middle_name, last_name
- email
- secondary_email
- profile_modify_date

<created_date>_person_addresses.csv

- create_date
- zip_name
- xml_file_name
- person_id
- address_start_date
- address_end_date
- address_type
- address_county
- address_city
- address_state_province
- address_zip_postal_code
- address_department
- address_street_address_1
- address_street_address_2

<created_date>_person_roles.csv

- create_date
- zip_name
- xml_file_name
- person_id
- role

**Comment by seanwiseman** [comment]
@de could we clarify the person data requirements here?

I can see bits and pieces across slack and email but wanted to confirm the final requirements before opening the PR to address [#17](https://github.com/elifesciences/data-pipeline/issues/17).

**Comment by de-code** [comment]
Yes, the intention of this issue was to clarify it. I've updated the description with a slightly modified version of Mat's proposal from the email and also added the role.

**Comment by seanwiseman** [comment]
@de If a `person-id` is not present for a `person` should it be skipped?

**Comment by de-code** [comment]
@seanwiseman Yes, I would say so. It should be raised as a warning so we know about it or could even make the process fail if necessary. I am not sure I ever encountered that case (I could check), have you?

**Comment by seanwiseman** [comment]
No not yet, just wondered.
